services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: Raamanand
      POSTGRES_PASSWORD: SR
      POSTGRES_DB: servicesdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: